name: works
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.0.6+10
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  http: ^0.13.3
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
